// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import DotsMenuController from "./dots_menu_controller"
application.register("dots-menu", DotsMenuController)

import FlashController from "./flash_controller"
application.register("flash", FlashController)

import ListsController from "./lists_controller"
application.register("lists", ListsController)

import MobileNavPopupController from "./mobile_nav_popup_controller"
application.register("mobile-nav-popup", MobileNavPopupController)

import ModalController from "./modal_controller"
application.register("modal", ModalController)

import NestedFormController from "./nested_form_controller"
application.register("nested-form", NestedFormController)

import SidebarController from "./sidebar_controller"
application.register("sidebar", SidebarController)

import SingleSelectController from "./single_select_controller"
application.register("single-select", SingleSelectController)

import TaskShowFormController from "./task_show_form_controller"
application.register("task-show-form", TaskShowFormController)

import ThemeSwitcherController from "./theme_switcher_controller"
application.register("theme-switcher", ThemeSwitcherController)
